[build]
  base = "crates/leptos-icons"
  command = """
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    source $HOME/.cargo/env && \
    rustup target add wasm32-unknown-unknown && \
    cargo install trunk wasm-bindgen-cli && \
    trunk build --release
  """
  publish = "dist"

[build.environment]
  CARGO_TERM_COLOR = "always"
  RUSTFLAGS = "--cfg=web_sys_unstable_apis"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
